"""
Notebook Generator Module
Creates a competition-ready Jupyter notebook (.ipynb) from the pipeline results.
"""

import json
import os
from typing import Optional


def _make_cell(cell_type: str, source: str | list[str], **kwargs) -> dict:
    """Create a Jupyter notebook cell."""
    if isinstance(source, str):
        source = source.split("\n")
    # Ensure each line (except last) ends with \n
    lines = []
    for i, line in enumerate(source):
        if i < len(source) - 1 and not line.endswith("\n"):
            lines.append(line + "\n")
        else:
            lines.append(line)

    cell = {
        "cell_type": cell_type,
        "metadata": {},
        "source": lines,
    }
    if cell_type == "code":
        cell["execution_count"] = None
        cell["outputs"] = []
    return cell


def generate_notebook(
    competition_rules: str,
    data_summary: str,
    target_column: str,
    id_column: Optional[str],
    problem_type: str,
    metric: Optional[str],
    quality_mode: str,
    n_folds: int,
    best_model_name: str,
    best_score: Optional[float],
    comparison_text: str,
    feature_engineering_log: str,
    ensemble_method: str,
    train_filename: str = "train.csv",
    test_filename: Optional[str] = "test_x.csv",
    output_dir: str = "outputs",
) -> str:
    """
    Generate a competition-ready Jupyter notebook.

    Returns the path to the saved .ipynb file.
    """
    cells = []

    # ── Title Cell ──
    cells.append(
        _make_cell(
            "markdown",
            [
                "# 🏆 KaggleForge Solution Notebook\n",
                "\n",
                f"**Problem Type:** {problem_type.title()}\n",
                f"**Target Column:** `{target_column}`\n",
                f"**Best Model:** {best_model_name}\n",
                f"**Best Score:** {best_score}\n",
                f"**Ensemble Method:** {ensemble_method}\n",
                "\n",
                "---\n",
                "\n",
                "This notebook was auto-generated by **KaggleForge**.\n",
                "It contains the full pipeline: data loading → feature engineering → model training → predictions.",
            ],
        )
    )

    # ── Competition Rules ──
    if competition_rules.strip():
        cells.append(
            _make_cell(
                "markdown",
                [
                    "## 📋 Competition Description\n",
                    "\n",
                    competition_rules,
                ],
            )
        )

    # ── Imports ──
    cells.append(
        _make_cell("markdown", ["## 1. Setup & Imports"])
    )
    cells.append(
        _make_cell(
            "code",
            [
                "import pandas as pd\n",
                "import numpy as np\n",
                "import warnings\n",
                "warnings.filterwarnings('ignore')\n",
                "\n",
                "# ML Libraries\n",
                "from pycaret.classification import ClassificationExperiment\n"
                if problem_type == "classification"
                else "from pycaret.regression import RegressionExperiment\n",
                "\n",
                "print('✅ All imports successful')",
            ],
        )
    )

    # ── Data Loading ──
    cells.append(
        _make_cell("markdown", ["## 2. Load Data"])
    )

    load_code = [
        f"train_df = pd.read_csv('{train_filename}')\n",
        f"print(f'Train shape: {{train_df.shape}}')\n",
        f"train_df.head()",
    ]
    if test_filename:
        load_code.insert(1, f"test_df = pd.read_csv('{test_filename}')\n")
        load_code.insert(2, f"print(f'Test shape: {{test_df.shape}}')\n")
    cells.append(_make_cell("code", load_code))

    # ── EDA ──
    cells.append(
        _make_cell("markdown", ["## 3. Exploratory Data Analysis"])
    )
    cells.append(
        _make_cell(
            "code",
            [
                "# Data types and missing values\n",
                "print('=== Data Types ===')\n",
                "print(train_df.dtypes)\n",
                "print()\n",
                "print('=== Missing Values ===')\n",
                "missing = train_df.isnull().sum()\n",
                "missing = missing[missing > 0]\n",
                "if len(missing) > 0:\n",
                "    print(missing)\n",
                "else:\n",
                "    print('No missing values!')\n",
                "print()\n",
                f"print('=== Target Distribution ({target_column}) ===')\n",
                f"print(train_df['{target_column}'].describe())",
            ],
        )
    )

    # ── Feature Engineering ──
    cells.append(
        _make_cell(
            "markdown",
            [
                "## 4. Feature Engineering\n",
                "\n",
                "Automated transformations applied:\n",
                "\n",
                "```\n",
                feature_engineering_log + "\n",
                "```",
            ],
        )
    )

    fe_code = [
        "# Feature engineering pipeline\n",
        "from core.feature_engineer import FeatureEngineer\n",
        "\n",
        "fe = FeatureEngineer()\n",
    ]
    if test_filename:
        fe_code.extend([
            f"train_fe, test_fe = fe.fit_transform(\n",
            f"    train_df, target_column='{target_column}',\n",
            f"    test_df=test_df, id_column={repr(id_column)}\n",
            f")\n",
        ])
    else:
        fe_code.extend([
            f"train_fe, _ = fe.fit_transform(\n",
            f"    train_df, target_column='{target_column}',\n",
            f"    id_column={repr(id_column)}\n",
            f")\n",
        ])
    fe_code.append("print(fe.get_summary())")
    cells.append(_make_cell("code", fe_code))

    # ── Model Training ──
    cells.append(
        _make_cell("markdown", ["## 5. Model Training & Comparison"])
    )

    exp_class = (
        "ClassificationExperiment"
        if problem_type == "classification"
        else "RegressionExperiment"
    )

    train_code = [
        f"# Initialize PyCaret experiment\n",
        f"exp = {exp_class}(\n",
        f"    target='{target_column}',\n",
        f"    session_id=42,\n",
        f"    fold={n_folds},\n",
        f"    verbose=False,\n",
        f"    normalize=True,\n",
        f")\n",
        f"exp.fit(train_fe)\n",
        f"print('✅ Experiment setup complete')",
    ]
    cells.append(_make_cell("code", train_code))

    # Compare models
    compare_code = [
        "# Compare all models\n",
        "result = exp.compare_models(verbose=False, turbo=False",
    ]
    if metric:
        compare_code[-1] += f", sort='{metric}'"
    compare_code[-1] += ")\n"
    compare_code.extend([
        "\n",
        "# Display leaderboard\n",
        "if hasattr(result, 'leaderboard'):\n",
        "    display(result.leaderboard)\n",
        "    best = result.best\n",
        "else:\n",
        "    best = result\n",
        "    display(exp.pull())",
    ])
    cells.append(_make_cell("code", compare_code))

    # Tune
    if quality_mode in ("standard", "competition"):
        cells.append(
            _make_cell(
                "code",
                [
                    "# Tune the best model\n",
                    "tuned = exp.tune_model(best, verbose=False, n_iter=20)\n",
                    "if hasattr(tuned, 'pipeline'):\n",
                    "    best = tuned.pipeline\n",
                    "else:\n",
                    "    best = tuned\n",
                    "print('✅ Model tuned')",
                ],
            )
        )

    # Ensemble
    if quality_mode == "competition":
        cells.append(
            _make_cell(
                "markdown",
                [
                    "### Ensemble\n",
                    f"Ensemble method used: **{ensemble_method}**",
                ],
            )
        )

    # Finalize
    cells.append(
        _make_cell(
            "code",
            [
                "# Finalize model (train on full dataset)\n",
                "final = exp.finalize_model(best)\n",
                "if hasattr(final, 'pipeline'):\n",
                "    final_model = final.pipeline\n",
                "else:\n",
                "    final_model = final\n",
                "print('✅ Model finalized')",
            ],
        )
    )

    # ── Results ──
    cells.append(
        _make_cell("markdown", ["## 6. Results & Analysis"])
    )
    cells.append(
        _make_cell(
            "code",
            [
                "# Model comparison summary\n",
                "comparison = exp.pull() if not hasattr(result, 'leaderboard') else result.leaderboard\n",
                "print('Model Comparison Results:')\n",
                "print(comparison.to_string())",
            ],
        )
    )

    # ── Predictions ──
    if test_filename:
        cells.append(
            _make_cell("markdown", ["## 7. Generate Predictions & Submission"])
        )
        cells.append(
            _make_cell(
                "code",
                [
                    "# Generate predictions\n",
                    "pred_result = exp.predict_model(final_model, data=test_fe)\n",
                    "if hasattr(pred_result, 'predictions'):\n",
                    "    predictions = pred_result.predictions\n",
                    "else:\n",
                    "    predictions = pred_result\n",
                    "\n",
                    "# Build submission\n",
                    "submission = pd.DataFrame()\n",
                    f"if '{id_column}' in test_df.columns:\n"
                    if id_column
                    else "if False:\n",
                    f"    submission['{id_column}'] = test_df['{id_column}']\n"
                    if id_column
                    else "    pass\n",
                    "\n",
                    "if 'prediction_label' in predictions.columns:\n",
                    f"    submission['{target_column}'] = predictions['prediction_label']\n",
                    "elif 'Label' in predictions.columns:\n",
                    f"    submission['{target_column}'] = predictions['Label']\n",
                    "\n",
                    "submission.to_csv('submission.csv', index=False)\n",
                    "print(f'Submission shape: {submission.shape}')\n",
                    "submission.head(10)",
                ],
            )
        )

    # ── Notebook structure ──
    notebook = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.11.0",
            },
        },
        "cells": cells,
    }

    # Save
    notebook_path = os.path.join(output_dir, "solution_notebook.ipynb")
    with open(notebook_path, "w", encoding="utf-8") as f:
        json.dump(notebook, f, indent=1, ensure_ascii=False)

    return notebook_path
